<h2>MENU</h2>
<div class="menu" id="main_menu">
    <a href="<?php echo $this->getBaseUrl('timetable/view/index'); ?>"><?php echo $this->tr('Timetables'); ?></a>
    <a href="<?php echo $this->getBaseUrl('teacher/view/index'); ?>"><?php echo $this->tr('Teachers'); ?></a>
    <a href="<?php echo $this->getBaseUrl('subject/view/index'); ?>"><?php echo $this->tr('Subjects'); ?></a>
    <a href="<?php echo $this->getBaseUrl('class/view/index'); ?>"><?php echo $this->tr('Classes'); ?></a>
</div>