<?php
/**
 * @var $this \Entities\Teacher\View
 */
?>
<?php $_teacher     = $this->getModel(); ?>
<?php $_fromBuilder = $this->formBuilder(); ?>
<h1><?php echo $this->tr('Teachers'); ?></h1>
<div class="wrapper">
    <div class="content">
        <form name="<?php echo $this->getEntityName(); ?>" id="<?php echo $this->getEntityName(); ?>" action="<?php echo $_fromBuilder->getActionUrl('save', $_teacher); ?>" method="POST" accept-charset="utf-8">
            <div>
                <ul>
                    <li>
                        <label for="name"><?php echo $this->tr('Name: ') ?></label>
                        <input id="name" type="text" name="<?php echo $_fromBuilder->getElementName('name'); ?>" value="<?php echo $_teacher->getData('name'); ?>"/>
                    </li>
                    <li>
                        <label for="lastname"><?php echo $this->tr('Lastname: ') ?></label>
                        <input id="lastname" type="text" name="<?php echo $_fromBuilder->getElementName('lastname'); ?>" value="<?php echo $_teacher->getData('lastname'); ?>"/>
                    </li>
                    <li>
                        <label for="middlename"><?php echo $this->tr('Middlename: ') ?></label>
                        <input id="middlename" type="text" name="<?php echo $_fromBuilder->getElementName('middlename'); ?>" value="<?php echo $_teacher->getData('middlename'); ?>"/>
                    </li>
                    <li>
                        <label for="subject_ids"><?php echo $this->tr('Subject: ') ?></label>
                        <?php echo $this->formBuilder()->getRelativeElementHtml(array('element_id' => 'subjects','element_name' => 'subjects', 'element_type' => 'multiple'), $_teacher, 'subject'); ?>
                    </li>
                </ul>
                <div>
                    <input type="submit" name="submit" value="<?php echo $this->tr('Submit form'); ?>" />
                </div>
            </div>
        </form>
    </div>
    <div class="right_column">
        <?php $teachers = $this->getTeachersList(); ?>
        <?php if($teachers->count() > 0) : ?>
            <ul>
            <?php foreach ($teachers as $teacher) : ?>
                <li>
                    <p><?php echo $teacher->getName(); ?> <?php echo $teacher->getLastname(); ?> <?php echo $teacher->getMiddlename(); ?></p>
                    <?php $subjects = $teacher->getSubjects(); ?>
                    <?php if(!empty($subjects)) : ?>
                        <ul>
                        <?php foreach($subjects as $subject) : ?>
                            <li><?php echo $subject->getName(); ?></li>
                        <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                    <a href="<?php echo $this->getBaseUrl('teacher/view/index', array($teacher->getEntityPrimaryKey() => $teacher->getEntityId())); ?>"><?php echo $this->tr('Edit'); ?></a>
                    <a href="<?php echo $_fromBuilder->getActionUrl('delete', $teacher); ?>"><?php echo $this->tr('Delete'); ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php else : ?>
            <p><?php echo $this->tr('There are no any teachers yet.'); ?></p>
        <?php endif; ?>
    </div>
</div>