<?php
/**
 * @var $this \Entities\Teacher\View
 */
?>
<?php $_teacher = $this->getModel(); ?>
<h1><?php echo $this->tr('Teachers'); ?></h1>
<div class="wrapper">
    <div class="content">
        <form name="<?php echo $this->getEntityName(); ?>" id="<?php echo $this->getEntityName(); ?>" action="<?php echo $this->getActionUrl('save', $_teacher); ?>" method="POST" accept-charset="utf-8">
            <div>
                <ul>
                    <li>
                        <label for="name"><?php echo $this->tr('Name: ') ?></label>
                        <input id="name" type="text" name="<?php echo $this->getInputName('name'); ?>" value="<?php echo $_teacher->getData('name'); ?>"/>
                    </li>
                    <li>
                        <label for="lastname"><?php echo $this->tr('Lastname: ') ?></label>
                        <input id="lastname" type="text" name="<?php echo $this->getInputName('lastname'); ?>" value="<?php echo $_teacher->getData('lastname'); ?>"/>
                    </li>
                    <li>
                        <label for="middlename"><?php echo $this->tr('Middlename: ') ?></label>
                        <input id="middlename" type="text" name="<?php echo $this->getInputName('middlename'); ?>" value="<?php echo $_teacher->getData('middlename'); ?>"/>
                    </li>
                    <li>
                        <label for="subject_ids"><?php echo $this->tr('Subject: ') ?></label>
                        <input id="subject_ids" type="text" name="<?php echo $this->getInputName('subject_ids'); ?>" value="<?php echo $_teacher->getData('subject_ids'); ?>"/>
                    </li>
                </ul>
                <div>
                    <input type="submit" name="submit" value="<?php echo $this->tr('Submit form'); ?>" />
                </div>
            </div>
        </form>
    </div>
    <div class="right_column">
        <?php if($teachers = $this->getTeachersList()) : ?>
            <ul>
            <?php foreach ($teachers as $teacher) : ?>
                <li>
                    <p><?php echo $teacher->getName(); ?> <?php echo $teacher->getLastname(); ?> <?php echo $teacher->getMiddlename(); ?></p>
                    <a href="<?php echo $this->getBaseUrl('teacher/view/index', array($teacher->getEntityPrimaryKey() => $teacher->getEntityId())); ?>"><?php echo $this->tr('Edit'); ?></a>
                    <a href="<?php echo $this->getActionUrl('delete', $teacher); ?>"><?php echo $this->tr('Delete'); ?></a>
                </li>
            <?php endforeach; ?>
            </ul>
        <?php else : ?>
            <p><?php echo $this->tr('There are no any teachers yet.'); ?></p>
        <?php endif; ?>
    </div>
</div>